import builtins from "builtin-modules";
import esbuild from "esbuild";
import { lessLoader } from "esbuild-plugin-less";
import process from "process";
import { copyFile, mkdir, readdir } from 'fs/promises';
import { join } from 'path';
import { pluginBuildConfig } from './pluginBuild.config.js';
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
async function copyDir(src, dest) {
	const entries = await readdir(src, { withFileTypes: true });
	await mkdir(dest, { recursive: true });

	for (const entry of entries) {
		const srcPath = join(src, entry.name);
		const destPath = join(dest, entry.name);

		if (entry.isDirectory()) {
			await copyDir(srcPath, destPath);
		} else {
			await copyFile(srcPath, destPath);
		}
	}
}

const copyPlugin = {
	name: 'copy-plugin',
	setup(build) {
		build.onEnd(async () => {
			try {
				// Copy files to all installation targets
				for (const targetPath of pluginBuildConfig.installTargets) {
					const pluginPath = `${targetPath}/.obsidian/plugins/my-plugin`;

					// Ensure plugin directory exists
					await mkdir(pluginPath, { recursive: true });

					// Copy configured files
					for (const file of pluginBuildConfig.copyFiles) {
						await copyFile(file, `${pluginPath}/${file}`);
					}

					// Copy .hotreload for personal vault
					if (targetPath.includes('obsidian-personal')) {
						await copyFile('.hotreload', `${pluginPath}/.hotreload`);
					}

					// Copy mockOb directory for test vault
					if (targetPath === 'test-vault-myplugin') {
						await copyDir('mockOb', targetPath);
					}

					console.log('✓ Plugin files copied successfully into', pluginPath);
				}
			} catch (error) {
				console.error('Error copying plugin files:', error);
				process.exit(1);
			}
		});
	},
};
/**
 * load css from imported modules
 */
const cssLoaderPlugin = {
	name: "css-loader",
	setup(build) {
		build.onLoad({ filter: /\.css$/ }, async (args) => {
			const { readFile } = await import("fs/promises");
			const contents = await readFile(args.path, "utf8");
			return {
				contents: `const style = document.createElement('style');
					 style.innerText = ${JSON.stringify(contents)};
					 document.head.appendChild(style);`,
				loader: "js", // Treat the output as JavaScript
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
		css: banner,
	},
	entryPoints: ["./src/main.ts", "./src/styles.less"],
	outdir: "./",
	// outfile: "main.js",
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	plugins: [cssLoaderPlugin, lessLoader(), copyPlugin],
	jsx: "automatic", // 'transform|automatic|null' "jsx": "react-jsx" in tsconfig.json
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
